[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
playground_solana_contracts = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

#[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[scripts]
test = "node --stack-trace-limit=10000 node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 --full-trace tests/**/*.ts"
