[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
playground_solana_contracts = "7AwuU7HNHrE2GgS4tRdZLdnJmG4Pz5HjgDkd7fDVtoLK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vsm/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
